"""Tenchi: a contract-first, Python-native application framework.

Canonical imports use the submodules — ``tenchi.contracts``,
``tenchi.routes``, ``tenchi.jobs``, ``tenchi.errors``, ``tenchi.server``,
``tenchi.client``, ``tenchi.retries``, ``tenchi.tools``
— and the most common names are re-exported here for convenience.
"""

from .client import (
    Client,
    ClientAttemptObserver,
    ClientAttemptOutcome,
    ClientObserver,
    ClientOutcome,
    ClientResponse,
    UnexpectedResponseError,
)
from .contracts import Contract, contract
from .errors import AppError, ConfigurationError, ErrorDef, TenchiError
from .execution import ExecutionError, UseCaseObserver, UseCaseOutcome, execute
from .health import health_route
from .idempotency import (
    IDEMPOTENCY_CONFLICT,
    IDEMPOTENCY_IN_PROGRESS,
    IdempotencyResultError,
    IdempotencyStore,
    IdempotencyStoreError,
    MemoryIdempotencyStore,
    fingerprint,
    run_idempotently,
)
from .jobs import (
    Job,
    JobBindingError,
    JobDispatcher,
    JobGroup,
    JobHandler,
    JobMessage,
    JobNotFoundError,
    JobResultError,
    create_job_dispatcher,
    job,
    job_group,
    job_handler,
    job_message,
)
from .openapi import openapi_route, openapi_schema, swagger_ui_route
from .pagination import Page, PageQuery, page
from .preflight import (
    PreflightBindingError,
    PreflightCheck,
    PreflightGroup,
    PreflightOutcome,
    PreflightReport,
    PreflightStatus,
    preflight_check,
    preflight_group,
    run_preflight,
)
from .rate_limits import (
    RATE_LIMITED,
    MemoryRateLimitStore,
    RateLimitExceeded,
    RateLimitPermit,
    RateLimitStore,
    RateLimitStoreError,
    enforce_rate_limit,
)
from .responses import PresentedResponse, ResponseDef, present, response
from .retries import RetryPolicy, RetryTimeoutError, retry_policy
from .routes import Route, RouteGroup, route, route_group
from .server import OutcomeObserver, RequestInfo, RequestOutcome, create_app
from .tasks import (
    Task,
    TaskBindingError,
    TaskGroup,
    TaskNotFoundError,
    TaskResultError,
    TaskRunner,
    create_task_runner,
    task,
    task_group,
)
from .tools import (
    TOOL_MANIFEST_VERSION,
    Tool,
    ToolBinding,
    ToolBindingError,
    ToolGroup,
    ToolInvocationError,
    ToolNotFoundError,
    ToolResultError,
    ToolRunner,
    create_tool_runner,
    tool,
    tool_group,
    tool_handler,
    tool_manifest,
)
from .webhooks import (
    Webhook,
    WebhookBindingError,
    WebhookRequest,
    WebhookVerifier,
    webhook,
)

__version__ = "0.11.0"

__all__ = [
    "IDEMPOTENCY_CONFLICT",
    "IDEMPOTENCY_IN_PROGRESS",
    "RATE_LIMITED",
    "TOOL_MANIFEST_VERSION",
    "AppError",
    "Client",
    "ClientAttemptObserver",
    "ClientAttemptOutcome",
    "ClientObserver",
    "ClientOutcome",
    "ClientResponse",
    "ConfigurationError",
    "Contract",
    "ErrorDef",
    "ExecutionError",
    "IdempotencyResultError",
    "IdempotencyStore",
    "IdempotencyStoreError",
    "Job",
    "JobBindingError",
    "JobDispatcher",
    "JobGroup",
    "JobHandler",
    "JobMessage",
    "JobNotFoundError",
    "JobResultError",
    "MemoryIdempotencyStore",
    "MemoryRateLimitStore",
    "OutcomeObserver",
    "Page",
    "PageQuery",
    "PreflightBindingError",
    "PreflightCheck",
    "PreflightGroup",
    "PreflightOutcome",
    "PreflightReport",
    "PreflightStatus",
    "PresentedResponse",
    "RateLimitExceeded",
    "RateLimitPermit",
    "RateLimitStore",
    "RateLimitStoreError",
    "RequestInfo",
    "RequestOutcome",
    "ResponseDef",
    "RetryPolicy",
    "RetryTimeoutError",
    "Route",
    "RouteGroup",
    "Task",
    "TaskBindingError",
    "TaskGroup",
    "TaskNotFoundError",
    "TaskResultError",
    "TaskRunner",
    "TenchiError",
    "Tool",
    "ToolBinding",
    "ToolBindingError",
    "ToolGroup",
    "ToolInvocationError",
    "ToolNotFoundError",
    "ToolResultError",
    "ToolRunner",
    "UnexpectedResponseError",
    "UseCaseObserver",
    "UseCaseOutcome",
    "Webhook",
    "WebhookBindingError",
    "WebhookRequest",
    "WebhookVerifier",
    "__version__",
    "contract",
    "create_app",
    "create_job_dispatcher",
    "create_task_runner",
    "create_tool_runner",
    "enforce_rate_limit",
    "execute",
    "fingerprint",
    "health_route",
    "job",
    "job_group",
    "job_handler",
    "job_message",
    "openapi_route",
    "openapi_schema",
    "page",
    "preflight_check",
    "preflight_group",
    "present",
    "response",
    "retry_policy",
    "route",
    "route_group",
    "run_idempotently",
    "run_preflight",
    "swagger_ui_route",
    "task",
    "task_group",
    "tool",
    "tool_group",
    "tool_handler",
    "tool_manifest",
    "webhook",
]
